version: '2'

services:
  ci:
    build: .
    environment:
      NPM_CONFIG_CACHE: /tmp/npm-cache
    volumes:
      - .:/app
      - node-modules:/app/node_modules
      - npm-cache:/tmp/npm-cache
    working_dir: /app

  dev:
    build: .
    environment:
      NPM_CONFIG_CACHE: /tmp/npm-cache
      AWS_LAMBDA_RUNTIME_API: runtime-api:3000
    volumes:
      - .:/app
      - node-modules:/app/node_modules
      - npm-cache:/tmp/npm-cache
    working_dir: /app
    command: auto/dev-runtime-cmd
    networks:
      internal:
    depends_on:
      - runtime-api

  runtime-api:
    build: .
    environment:
      NPM_CONFIG_CACHE: /tmp/npm-cache
    volumes:
      - .:/app
      - node-modules:/app/node_modules
      - npm-cache:/tmp/npm-cache
    working_dir: /app
    command: sh -c "npm install && node runtime-api/server"
    networks:
      internal:

networks:
  internal:

volumes:
  node-modules:
  npm-cache:
