version: '2'

services:
  ci:
    build: .
    environment:
      NPM_CONFIG_CACHE: /tmp/npm-cache
    volumes:
      - .:/app
      - node-modules:/app/node_modules
      - npm-cache:/tmp/npm-cache
    working_dir: /app

  dev-runtime:
    build: .
    environment:
      NPM_CONFIG_CACHE: /tmp/npm-cache
      AWS_LAMBDA_RUNTIME_API: runtime-api:3000
    volumes:
      - .:/app
      - node-modules:/app/node_modules
      - npm-cache:/tmp/npm-cache
    working_dir: /app
    command: auto/dev-runtime-cmd
    networks:
      internal:
    depends_on:
      - runtime-api

  dev-runtime-docker:
    build: test
    environment:
      AWS_LAMBDA_FUNCTION_NAME: test-function-name
      AWS_LAMBDA_FUNCTION_VERSION: test-function-version
      AWS_LAMBDA_FUNCTION_MEMORY_SIZE: 128
      AWS_LAMBDA_LOG_GROUP_NAME: test-log-group-name
      AWS_LAMBDA_LOG_STREAM_NAME: test-log-stream-name
      AWS_LAMBDA_RUNTIME_API: runtime-api:3000
    networks:
      internal:
    depends_on:
      - runtime-api

  runtime-api:
    image: node:15.14.0-buster-slim
    environment:
      NPM_CONFIG_CACHE: /tmp/npm-cache
    volumes:
      - .:/app
      - node-modules:/app/node_modules
      - npm-cache:/tmp/npm-cache
    working_dir: /app
    command: sh -c "npm install && node runtime-api/server"
    networks:
      internal:

networks:
  internal:

volumes:
  node-modules:
  npm-cache:
