#!/bin/sh

DIR="$( cd "$( dirname "$0" )" && pwd )"

export _HANDLER=hello.handler
export LAMBDA_TASK_ROOT="${DIR}/.."

export AWS_LAMBDA_FUNCTION_NAME=test-function-name
export AWS_LAMBDA_FUNCTION_VERSION=test-function-version
export AWS_LAMBDA_FUNCTION_MEMORY_SIZE=128
export AWS_LAMBDA_LOG_GROUP_NAME=test-log-group-name
export AWS_LAMBDA_LOG_STREAM_NAME=test-log-stream-name

cd "${DIR}/.."

sleep 5
exec "./stage/work/bootstrap"
