#!/bin/sh

set -ex

export NODE_VERSION=14.8.0
export SHA256=c7761fe5d56d045d1540b1f0bc8a20d7edf03e6fd695ee5fbffc1dd9416ccc75

DIR="$( cd "$( dirname "$0" )" && pwd )"

cd "${DIR}/.."

docker-compose build
docker-compose run --rm \
  -e NODE_VERSION -e SHA256 \
  package
