#!/bin/sh

set -ex

export NODE_VERSION=14.0.0
export SHA256=a2aaaa621074e1b56bb751bda53ce726319fac617587443371c0a7742481e5b6

DIR="$( cd "$( dirname "$0" )" && pwd )"

cd "${DIR}/.."

docker-compose build
docker-compose run --rm \
  -e NODE_VERSION -e SHA256 \
  package
