#!/bin/bash

set -xe

DIR="$( cd "$( dirname "$0" )" && pwd )"

cd "${DIR}/.."

# https://docs.aws.amazon.com/general/latest/gr/lambda-service.html
REGIONS="
sa-east-1
us-east-1
us-east-2
us-west-1
us-west-2
"

TMP="deployment-$(date +%s).txt"
for R in $REGIONS ; do
  echo "Deploying in ${R}"
  docker run -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY --rm \
    -w /app \
    -v $(pwd):/app \
    janaz/aws-cli:1.18.41-alpine \
    lambda publish-layer-version \
      --region "${R}" \
      --layer-name node-14-runtime \
      --description "nodejs-14.1.0 aws-cli-2.667.0" \
      --compatible-runtimes provided \
      --license-info Apache-2.0 \
      --zip-file fileb://stage/layer.zip
done | tee "$TMP"

set +x
# Markdown release notes
echo "|Region|Layer arn|"
echo "|--|--|"
cat "$TMP" | grep LayerVersionArn | cut -d '"' -f4 | while read L; do
  R=$(echo $L | cut -d: -f4)
  echo "|$R|\`$L\`|"
done
