#!/bin/bash

set -xe

DIR="$( cd "$( dirname "$0" )" && pwd )"

cd "${DIR}/.."

# https://docs.aws.amazon.com/general/latest/gr/lambda-service.html
REGIONS="
af-south-1
ap-east-1
ap-northeast-1
ap-northeast-2
ap-south-1
ap-southeast-1
ap-southeast-2
ca-central-1
eu-central-1
eu-north-1
eu-south-1
eu-west-1
eu-west-2
eu-west-3
me-south-1
sa-east-1
us-east-1
us-east-2
us-west-1
us-west-2
"

TMP="deployment-$(date +%s).txt"
LAYER_NAME=node-14-runtime
for R in $REGIONS ; do
  echo "Deploying in ${R}"
  docker run -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY --rm \
    -w /app \
    -v $(pwd):/app \
    janaz/aws-cli:1.18.41-alpine \
    lambda publish-layer-version \
      --region "${R}" \
      --layer-name "${LAYER_NAME}" \
      --description "nodejs-14.7.0 aws-cli-2.729.0" \
      --compatible-runtimes provided \
      --license-info Apache-2.0 \
      --zip-file fileb://stage/layer.zip

    echo "Getting the version number"
    layer_version=$(docker run -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY --rm \
      -w /app \
      -v $(pwd):/app \
      janaz/aws-cli:1.18.41-alpine \
      lambda list-layer-versions \
        --region "${R}" \
        --layer-name "${LAYER_NAME}" \
        --query 'max_by(LayerVersions, &Version).Version' \
        --output text)

    echo "Setting permissions for the layer"
    docker run -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY --rm \
      -w /app \
      -v $(pwd):/app \
      janaz/aws-cli:1.18.41-alpine \
      lambda add-layer-version-permission \
        --region "${R}" \
        --layer-name "${LAYER_NAME}" \
        --version-number "${layer_version}" \
        --statement-id share-with-all-accounts \
        --principal '*' \
        --action 'lambda:GetLayerVersion'

done | tee "$TMP"

set +x
# Markdown release notes
echo "|Region|Layer arn|"
echo "|--|--|"
cat "$TMP" | grep LayerVersionArn | cut -d '"' -f4 | while read L; do
  R=$(echo $L | cut -d: -f4)
  echo "|$R|\`$L\`|"
done
